###
version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: wordpress-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '4306:3306'
    networks:
      - net-wordpress
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Hermione57
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=Hermione57
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-debian
    volumes:
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/uploads:/var/www/html/wp-content/uploads
    ports:
      - '8000:80'
    networks:
      - net-wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=Hermione57
      - WORDPRESS_DB_NAME=wordpress

###
networks:
    net-wordpress:
        external: true
